import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const font = Geologica({ weight: "300", subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Script src="https://app.curbcutos.com/javascript/fa.js"></Script>
      <body className={font.className}>{children}</body>
    </html>
  );
}
